'use client';
import React, { useState } from 'react';
import { 
  Bell, Sparkles, Layers, Cpu, 
  ShieldCheck, HelpCircle, Database, LogOut
} from 'lucide-react';

export default function SVXCommandsDashboard() {
  const [activeTab, setActiveTab] = useState('On Going');

  const tabs = ['On Going', 'Up Coming', 'Ended', 'Canceled'];

  // ==========================================
  // CONFIGURACIÓN DINÁMICA CON TEXTO RESPONSIVO (Doble propósito)
  // ==========================================
  const bannerContent = {
    'On Going': {
      title: 'SVX Central Ingestion Engine',
      description: {
        short: 'SVX Command infrastructure for the massive, intelligent ingestion of technical catalogs and inventories from EXCEL and CSV formats into a single standardized workflow.',
        p1: 'This infrastructure serves as the high-volume data reception core of the platform, specifically engineered to resolve the operational chaos caused by multiple heterogeneous sources. The engine fully unifies the ingestion of massive technical catalogs and corporate inventories, processing complex data architectures like deeply nested EXCEL files and unstructured, massive CSV schemas into a single, standardized, high-availability input stream.',
        p2: 'Under the real-time monitoring of SVX Command, this ingestion phase ensures an optimal transfer rate and minimal latency using asynchronous processing queues. SVX Command actively supervises the status of input channels, managing memory allocations and ensuring that data provisioning remains continuous, secure, and completely transparent before routing it to the transformation layers.'
      },
      buttonText: 'View Ingestion Status',
      icon: <Layers className="w-3.5 h-3.5 text-[#484B97]" />,
      gradient: 'bg-gradient-to-r from-white via-[#F5F7FF] to-[#EDF2FF] border-[#D2D6E8]',
      textColor: 'text-[#242424]',
      btnBg: 'bg-[#484B97] hover:bg-[#5B5FC7] text-white transition-all rounded-sm',
    },
    'Up Coming': {
      title: 'Automated ETL Pipelines',
      description: {
        short: 'Unified console within SVX Command for the automated, real-time execution of pipelines, processing ETL workflows to eliminate manual data manipulation.',
        p1: 'The automated orchestration phase represents the optimization of data flows through continuous extraction, transformation, and deep cleaning (ETL) pipelines operating in real time. This system enforces strict business logic, normalizes units of measure, enriches technical attributes, and eliminates duplicate or corrupt records—completely eradicating manual intervention and mitigating operational risks within corporate databases.',
        p2: 'This entire sequence is centrally governed by SVX Command, acting as the master administration console. From SVX Command, automated triggers are configured, task concurrency is managed, and the workload of processing agents is optimized, ensuring that purified data is predictively available for subsequent analysis or external synchronization.'
      },
      buttonText: 'Monitor Pipelines',
      icon: <Cpu className="w-3.5 h-3.5 text-[#5B5FC7]" />,
      gradient: 'bg-gradient-to-r from-white via-[#F5F7FF] to-[#EDF2FF] border-[#D2D6E8]',
      textColor: 'text-[#242424]',
      btnBg: 'bg-[#484B97] hover:bg-[#5B5FC7] text-white transition-all rounded-sm',
    },
    'Ended': {
      title: 'CET Intelligent Auditing',
      description: {
        short: 'Automated audits managed via SVX Copilot and visualized in SVX Command to validate the semantic and taxonomic integrity of catalogs.',
        p1: 'This section focuses on quality assurance, data governance, and rigorous validation powered by advanced Artificial Intelligence algorithms. Every technical catalog and data structure that completes processing undergoes an automated audit driven by SVX Copilot, which evaluates taxonomic consistency, link integrity, and strict compliance with the global corporate standards required by Servex US before authorizing consolidation.',
        p2: 'SVX Command consolidates the complete historical record of these intelligent audits, serving as the definitive panel for operational visibility and forensic auditing. By interacting with SVX Command, engineers can analyze the accuracy metrics generated by the Copilot, review automatically corrected discrepancies, and validate compliance reports, ensuring that only data with absolute confidence levels is injected into the production environment.'
      },
      buttonText: 'Review Audits',
      icon: <ShieldCheck className="w-3.5 h-3.5 text-[#616161]" />,
      gradient: 'bg-gradient-to-r from-white via-[#FAF9F8] to-[#F3F2F1] border-[#E0E0E0]',
      textColor: 'text-[#242424]',
      btnBg: 'bg-[#616161] hover:bg-[#484848] text-white transition-all rounded-sm',
    },
    'Canceled': {
      title: 'Operational Support & Control',
      description: {
        short: 'Exception control center within SVX Command secured by Azure OAuth to mitigate risks, track error logs, and recover interrupted data streams.',
        p1: 'The operational support and control module is dedicated to ecosystem resilience, enterprise security, and proactive technical risk mitigation. It implements a robust security architecture based on perimeter authentication via Azure OAuth to restrict access, while providing expert-level support to isolate critical failures in unresolved transmissions, preventing isolated incidents from compromising system stability.',
        p2: 'Through SVX Command, system administrators have access to a highly advanced exception control center that centralizes structured error logs, debugging traces, and security alerts. SVX Command enables meticulous tracking of canceled or interrupted processes, providing intelligent retry tools and root-cause analysis to ensure total control and a swift return to an optimal operational state.'
      },
      buttonText: 'View Exception Logs',
      icon: <HelpCircle className="w-3.5 h-3.5 text-[#7A7574]" />,
      gradient: 'bg-gradient-to-r from-white via-[#FBFBFA] to-[#F5F4F3] border-[#E1DFDD]',
      textColor: 'text-[#242424]',
      btnBg: 'bg-[#7A7574] hover:bg-[#615E5C] text-white transition-all rounded-sm',
    }
  };

  const currentBanner = bannerContent[activeTab] || bannerContent['On Going'];

  const analyticsMetrics = [
    { label: 'Manual Excel Interventions', value: '0 Pending', change: '-180h/mo manual labor', changeColor: 'text-[#107C41]', icon: <Database className="w-3.5 h-3.5 text-[#025A9E]" /> },
    { label: 'Automated ETL Volume', value: '4.2 TB Ingested', change: 'XML • CSV • PDF unified', changeColor: 'text-[#464775]', icon: <Cpu className="w-3.5 h-3.5 text-[#464775]" /> },
    { label: 'AI Audited Compliance', value: '99.8% Perfect', change: '0 structural anomalies', changeColor: 'text-[#107C41]', icon: <ShieldCheck className="w-3.5 h-3.5 text-[#107C41]" /> },
  ];

  const [isModalOpen, setIsModalOpen] = useState(false);

  return (
    <div className="w-full h-auto bg-[#FFF] font-sans antialiased text-[#242424] p-4 space-y-4">
      
      {/* HEADER DINÁMICO RESPONSIVO (< 700px) */}
      <header className="flex items-center justify-between max-[700px]:justify-end bg-white border border-[#E0E0E0] rounded-md p-4 shadow-2xs">
        
        {/* LOGO Y TEXTOS: Se borran por completo si la pantalla mide menos de 700px */}
        <div className="flex items-center gap-3 max-[700px]:hidden">
          <img src="/logo.png" alt="SVX Commands Logo" className="h-7 w-auto object-contain" />
          <div className="flex flex-col border-l border-[#E0E0E0] pl-3">
            <span className="text-xs font-bold text-[#242424]">Svx Copilot System</span>
            <span className="text-[10px] text-[#616161]">Gestión inteligente de catálogos técnicos.</span>
          </div>
        </div>

        {/* CONTROLES / BOTÓN SIGN OUT */}
        <div className="flex items-center gap-2">
          {/* Tag de Cluster: Se oculta en móvil para dar prioridad al botón */}
          <span className="text-[10px] font-mono font-bold bg-[#EDEBE9] text-[#242424] px-2 py-1 rounded-sm border border-[#D2D0CE] max-[700px]:hidden">
            CLUSTER: PROD-US-EAST
          </span>


        </div>
      </header>

      {/* ANALYTICS BAR */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {analyticsMetrics.map((metric, i) => (
          <div key={i} className="bg-white border border-[#E0E0E0] rounded-md p-2.5 flex items-center justify-between shadow-2xs">
            <div className="space-y-0.5">
              <span className="text-[9px] font-bold text-[#616161] uppercase tracking-wider">{metric.label}</span>
              <div className="text-xs font-bold text-[#242424] tracking-tight">{metric.value}</div>
            </div>
            <div className="text-right flex flex-col items-end gap-0.5">
              <div className="p-1.5 bg-[#F3F2F1] rounded-sm border border-[#EDEBE9]">{metric.icon}</div>
              <span className={`text-[9px] font-medium ${metric.changeColor}`}>{metric.change}</span>
            </div>
          </div>
        ))}
      </div>

      {/* WORKSPACE */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-4 items-start">
        <div className="lg:col-span-12 space-y-4">
          
          {/* TABS FILTER */}
          <div className="w-full flex gap-1 border-b border-[#E0E0E0] bg-white px-2 rounded-t-md pt-1 overflow-x-auto no-scrollbar">
            {tabs.map((tab) => {
              const isActive = activeTab === tab;
              return (
                <button
                  key={tab}
                  onClick={() => setActiveTab(tab)}
                  className={`px-3 py-2 text-xs font-medium shrink-0 transition-all duration-150 relative focus:outline-none
                    ${isActive 
                      ? 'text-[#464775] font-bold after:absolute after:bottom-0 after:left-0 after:right-0 after:h-[2px] after:bg-[#464775]' 
                      : 'text-[#616161] hover:text-[#242424] hover:bg-[#F3F2F1] rounded-t-md'
                    }`}
                >
                  {tab}
                </button>
              );
            })}
          </div>

          {/* DYNAMIC AI BANNER RESPONSIVO */}
          <section className={`w-full rounded-md border p-4 transition-all duration-300 shadow-2xs ${currentBanner.gradient}`}>
            <div className="flex items-start justify-between">
              <div className="space-y-1 w-full">
                <div className="flex items-center gap-2 mb-2">
                  <div className="w-5 h-5 rounded-sm bg-[#242424]/5 flex items-center justify-center shrink-0">
                    {currentBanner.icon}
                  </div>
                  <h2 className={`text-xs font-bold uppercase tracking-wider ${currentBanner.textColor}`}>
                    {currentBanner.title}
                  </h2>
                </div>
                
                <div className="text-[11px] text-[#505050] font-light leading-relaxed">
                  <p className="block md:hidden text-justify italic">
                    {currentBanner.description.short}
                  </p>
                  <div className="hidden md:block space-y-3">
                    <p className="text-justify">{currentBanner.description.p1}</p>
                    <p className="text-justify">{currentBanner.description.p2}</p>
                  </div>
                </div>

              </div>
            </div>
            <div className="mt-4">
              <button 
                onClick={() => setIsModalOpen(true)}
                className={`inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold rounded-sm transition-colors duration-150 focus:outline-none shadow-3xs ${currentBanner.btnBg}`}
              >
                <Sparkles className="w-3.5 h-3.5" />
                {currentBanner.buttonText}
              </button>
            </div>
          </section>

        </div>
      </div>

      {/* POPUP COMPLETAMENTE VACÍO */}
      {isModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/40 backdrop-blur-xs transition-opacity duration-200">
          <div className="absolute inset-0" onClick={() => setIsModalOpen(false)} />
          <div className="relative w-[70vw] h-[70vh] bg-white border border-[#E0E0E0] rounded-lg shadow-2xl flex flex-col overflow-hidden animate-in fade-in zoom-in-95 duration-150">
            <button 
              onClick={() => setIsModalOpen(false)}
              className="absolute top-4 right-4 z-50 p-1 rounded-md text-slate-400 hover:bg-slate-100 hover:text-slate-600 transition-colors border border-slate-100"
            >
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
            <div className="flex-1 w-full h-full overflow-y-auto p-6"></div>
          </div>
        </div>
      )}

    </div>
  );
}